CREATE OR REPLACE WAREHOUSE ENERGY_WH
WITH
WAREHOUSE_SIZE = 'XSMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

CREATE OR REPLACE DATABASE ENERGY_ANALYTICS_DB;

CREATE OR REPLACE SCHEMA RAW_LAYER;

CREATE OR REPLACE SCHEMA STAGING_LAYER;

CREATE OR REPLACE SCHEMA ANALYTICS_LAYER;


USE WAREHOUSE ENERGY_WH;

USE DATABASE ENERGY_ANALYTICS_DB;

USE SCHEMA RAW_LAYER;

CREATE OR REPLACE TABLE CUSTOMER_RAW (
    customerId STRING,
    customerName STRING,
    meterNumber STRING,
    city STRING,
    customerType STRING,
    customerStatus STRING
);

CREATE OR REPLACE TABLE METER_READING_RAW (
    readingId STRING,
    customerId STRING,
    unitsConsumed NUMBER,
    readingDate DATE,
    readingStatus STRING
);

CREATE OR REPLACE TABLE BILLING_TRANSACTION_RAW (
    transactionId STRING,
    customerId STRING,
    billAmount NUMBER,
    dueDate DATE,
    paymentStatus STRING
);

CREATE OR REPLACE TABLE POWER_STATION_RAW (
    stationId STRING,
    stationName STRING,
    location STRING,
    operationalStatus STRING
);

CREATE OR REPLACE TABLE CONSUMPTION_ALERT_RAW (
    alertId STRING,
    customerId STRING,
    alertReason STRING,
    consumptionScore NUMBER,
    alertStatus STRING
);

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"';

CREATE OR REPLACE STAGE ENERGY_STAGE
FILE_FORMAT = CSV_FORMAT;
SHOW STAGES;



COPY INTO CUSTOMER_RAW
FROM @ENERGY_STAGE/customers.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO METER_READING_RAW
FROM @ENERGY_STAGE/meter_readings.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO BILLING_TRANSACTION_RAW
FROM @ENERGY_STAGE/billing_transactions.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO POWER_STATION_RAW
FROM @ENERGY_STAGE/power_station.csv
FILE_FORMAT = CSV_FORMAT;

COPY INTO CONSUMPTION_ALERT_RAW
FROM @ENERGY_STAGE/consumption_alert.csv
FILE_FORMAT = CSV_FORMAT;

SELECT meterNumber,
       COUNT(*)
FROM CUSTOMER_RAW
GROUP BY meterNumber
HAVING COUNT(*) > 1;

SELECT *
FROM METER_READING_RAW
WHERE unitsConsumed < 0;

SELECT *
FROM BILLING_TRANSACTION_RAW
WHERE billAmount <= 0;

SELECT *
FROM BILLING_TRANSACTION_RAW B
JOIN CUSTOMER_RAW C
ON B.customerId = C.customerId
WHERE C.customerStatus = 'Inactive';

USE SCHEMA ANALYTICS_LAYER;

CREATE OR REPLACE TABLE DIM_CUSTOMER AS
SELECT DISTINCT
    customerId,
    customerName,
    meterNumber,
    city,
    customerType,
    customerStatus
FROM RAW_LAYER.CUSTOMER_RAW;

CREATE OR REPLACE TABLE DIM_POWER_STATION AS
SELECT DISTINCT
    stationId,
    stationName,
    location,
    operationalStatus
FROM RAW_LAYER.POWER_STATION_RAW;

CREATE OR REPLACE TABLE FACT_BILLING AS
SELECT
    transactionId,
    B.customerId,
    billAmount,
    dueDate,
    paymentStatus,
    customerType,
    city
FROM RAW_LAYER.BILLING_TRANSACTION_RAW B
JOIN DIM_CUSTOMER C
ON B.customerId = C.customerId;

CREATE OR REPLACE TABLE FACT_METER_READING AS
SELECT
    readingId,
    M.customerId,
    unitsConsumed,
    readingDate,
    readingStatus,
    city,
    customerType
FROM RAW_LAYER.METER_READING_RAW M
JOIN DIM_CUSTOMER C
ON M.customerId = C.customerId;

USE SCHEMA ANALYTICS_LAYER;

CREATE OR REPLACE VIEW VW_BILLING_SUMMARY AS
SELECT
    customerId,
    city,
    customerType,
    SUM(billAmount) AS total_bill,
    COUNT(transactionId) AS total_transactions
FROM FACT_BILLING
GROUP BY customerId, city, customerType;

CREATE OR REPLACE VIEW VW_CONSUMPTION_SUMMARY AS
SELECT
    customerId,
    city,
    customerType,
    AVG(unitsConsumed) AS avg_consumption,
    MAX(unitsConsumed) AS max_consumption,
    SUM(unitsConsumed) AS total_consumption
FROM FACT_METER_READING
GROUP BY customerId, city, customerType;

CREATE OR REPLACE VIEW VW_HIGH_USAGE_ALERTS AS
SELECT
    customerId,
    unitsConsumed,
    readingDate,
    CASE
        WHEN unitsConsumed > 800 THEN 'HIGH_USAGE'
        ELSE 'NORMAL'
    END AS usage_status
FROM FACT_METER_READING;

CREATE OR REPLACE VIEW VW_REVENUE_ANALYSIS AS
SELECT
    city,
    customerType,
    SUM(billAmount) AS revenue,
    AVG(billAmount) AS avg_bill
FROM FACT_BILLING
GROUP BY city, customerType;

CREATE OR REPLACE VIEW MV_CITY_REVENUE AS
SELECT
    city,
    SUM(billAmount) AS total_revenue
FROM FACT_BILLING
GROUP BY city;

CREATE OR REPLACE VIEW MV_CONSUMPTION_TREND AS
SELECT
    customerType,
    AVG(unitsConsumed) AS avg_units
FROM FACT_METER_READING
GROUP BY customerType;

USE SCHEMA RAW_LAYER;

CREATE OR REPLACE TABLE ENERGY_JSON_RAW (
    RAW_DATA VARIANT
);

CREATE OR REPLACE FILE FORMAT JSON_FORMAT
TYPE = JSON;

CREATE OR REPLACE STAGE JSON_STAGE
FILE_FORMAT = JSON_FORMAT;

COPY INTO ENERGY_JSON_RAW
FROM @JSON_STAGE;

SELECT
    RAW_DATA:customerId::STRING AS customer_id,
    RAW_DATA:unitsConsumed::NUMBER AS units_consumed,
    RAW_DATA:city::STRING AS city
FROM ENERGY_JSON_RAW;

USE SCHEMA RAW_LAYER;

CREATE OR REPLACE STREAM METER_READING_STREAM
ON TABLE METER_READING_RAW;

SELECT *
FROM METER_READING_STREAM;

INSERT INTO METER_READING_RAW
VALUES
('R999','C101',950,'2026-05-15','VALID');

USE SCHEMA ANALYTICS_LAYER;

CREATE OR REPLACE TABLE HIGH_USAGE_ALERT_TABLE (
    customerId STRING,
    unitsConsumed NUMBER,
    alert_time TIMESTAMP
);

CREATE OR REPLACE TASK HIGH_USAGE_TASK
WAREHOUSE = ENERGY_WH
SCHEDULE = '1 MINUTE'
AS
INSERT INTO HIGH_USAGE_ALERT_TABLE
SELECT
    customerId,
    unitsConsumed,
    CURRENT_TIMESTAMP()
FROM RAW_LAYER.METER_READING_STREAM
WHERE unitsConsumed > 800;

ALTER TASK HIGH_USAGE_TASK RESUME;

CREATE OR REPLACE DYNAMIC TABLE DT_DAILY_CONSUMPTION
TARGET_LAG = '1 minute'
WAREHOUSE = ENERGY_WH
AS
SELECT
    customerId,
    SUM(unitsConsumed) AS total_units
FROM RAW_LAYER.METER_READING_RAW
GROUP BY customerId;

SELECT *
FROM DT_DAILY_CONSUMPTION;
